### ISSUE TITLE
Remove/repurpose constants.py

### ISSUE THREAD

**Issue by myrakrusemark** [myrakrusemark/Daisy-openAI-chat#8]
Constants.py may no longer be needed, except for localization, if even that.

Move any necessary items to configs.yaml and refactor code that uses it

Move any start prompts to new individual code-hook modules at new code hook "Main_messages_start" in Main.py

**Comment by HiraduNakamura** [comment]
Submitted PR

**Comment by myrakrusemark** [comment]
Updates must be made in the branch associated with that issue.
